### ISSUE TITLE
using usb/ip with Amazon Kindle

### ISSUE THREAD

**Issue by tadabrowski** [vadimgrn/usbip-win2#10]
Hi!

I'm trying to use usb/ip with the Amazon Kindle without any luck.

Binding seems to be successful, the drive shows, but it's not accessible. Moreover the Kindle seems to be in some kind of loop like it was being connected and disconnected continuously.

The server is running on Ubuntu. I noticed disturbing logs from dmesg.

![image](https://user-images.githubusercontent.com/12089949/177850847-e80d36c2-9b24-45ef-a582-ae1d06d035cf.png)

**Comment by vadimgrn** [comment]
Hi, could you please add debug information as described [here](https://github.com/vadimgrn/usbip-win2/tree/develop#obtaining-usbip-logs-on-windows)? I can do nothing without the log of the driver.

**Comment by tadabrowski** [comment]
Can you help me a bit?

First of all I'm having problems with installing the debug build. The vcruntime140_1d is missing.

Secondly, I'm not a cpp developer so I'm not familiar with any tools. What should be exactly installed? Is Windows Driver Kit enough?

**Comment by vadimgrn** [comment]
OK, I'll explain a bit later.

**Comment by vadimgrn** [comment]
I've fixed dependency issue, now you will be able to install debug build that I attached to this message. To run executables from tracelog.zip you should install [MICROSOFT VISUAL C++ 2015 - 2022 RUNTIME ](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
[tracelog.zip](https://github.com/vadimgrn/usbip-win2/files/9076085/tracelog.zip)
[usbip-win2-0.9.0.1-Debug.zip](https://github.com/vadimgrn/usbip-win2/files/9076086/usbip-win2-0.9.0.1-Debug.zip)
)

**Comment by tadabrowski** [comment]
Done. 
[tracelog-logs.zip](https://github.com/vadimgrn/usbip-win2/files/9076553/tracelog-logs.zip)

**Comment by vadimgrn** [comment]
Could you pls gather log one more time? It's also interesting if it works as usual flash drive (if do not use dedicated app).
[usbip-win2-0.9.0.1-Debug.zip](https://github.com/vadimgrn/usbip-win2/files/9078862/usbip-win2-0.9.0.1-Debug.zip)

**Comment by vadimgrn** [comment]
Try this build, please
[usbip-win2-0.9.1.0-Debug.zip](https://github.com/vadimgrn/usbip-win2/files/9173653/usbip-win2-0.9.1.0-Debug.zip)

**Comment by unrivaledrides** [comment]
Ok, here's a Camera hang. It works for 3-4 minutes, then drops. The other devices (PMU, Dash) don't drop. Just the Camera, when I'm doing "live mode" where it downloads the video image in near real-time.

[usbip-cameraHang.zip](https://github.com/vadimgrn/usbip-win2/files/9173999/usbip-cameraHang.zip)

**Comment by vadimgrn** [comment]
The user didn't respond

**Comment by tadabrowski** [comment]
Just tried it... still no success.

Symptoms are exactly the same. "My computer" window shows a new disk, but the window freezes shortly after opening. The Kindle acts like it's being connected and disconnected all the time.

Do you need debug logs?

**Comment by vadimgrn** [comment]
yes

**Comment by tadabrowski** [comment]
Done.
[tracelog-logs-120822.zip](https://github.com/vadimgrn/usbip-win2/files/9315398/tracelog-logs-120822.zip)

I noticed some bug while generating logs. I don't know why this path is used.
WPPFMT : error : 0x2 loading D:\usbip-win2\x64\Debug\usbip_vhci.pdb.

**Comment by vadimgrn** [comment]
`    Start a log session for vhci driver (copy commands to .bat file and run it)

@echo off
set NAME=usbip-vhci
tracelog.exe -stop %NAME%
tracepdb.exe -f "C:\Program Files\usbip-win2\*.pdb" -s -p %TEMP%\%NAME%
tracelog.exe -start %NAME% -guid #8b56380d-5174-4b15-b6f4-4c47008801a4 -f %NAME%.etl -flag 0x3F -level 5

    Reproduce the issue
    Stop the log session and get plain text log (copy commands to .bat file and run it)

@echo off
set NAME=usbip-vhci
set TRACE_FORMAT_PREFIX=[%%9]%%3!04x! %%!LEVEL! %%!FUNC!:
tracelog.exe -stop %NAME%
tracefmt.exe -nosummary -p %TEMP%\%NAME% -o %NAME%.txt %NAME%.etl
rem sed -i 's/TRACE_LEVEL_CRITICAL/CRT/;s/TRACE_LEVEL_ERROR/ERR/;s/TRACE_LEVEL_WARNING/WRN/;s/TRACE_LEVEL_INFORMATION/INF/;s/TRACE_LEVEL_VERBOSE/VRB/' %NAME%.txt
rem rm sed*
`
[usbip-win2-0.9.2.0-Debug.zip](https://github.com/vadimgrn/usbip-win2/files/9315955/usbip-win2-0.9.2.0-Debug.zip)

**Comment by vadimgrn** [comment]
The device returns an EPIPE error for all subsequent transfers after it has not received any bytes for read request. Unfortunately, I don't know what to fix because it isn't obvious. There is something wrong in the driver, but what... May be this issue will gone in one of future release.

**Comment by vadimgrn** [comment]
Try this build, pls
[usbip-win2-0.9.2.0-Debug.zip](https://github.com/vadimgrn/usbip-win2/files/9388788/usbip-win2-0.9.2.0-Debug.zip)

**Comment by tadabrowski** [comment]
I don't know if I generated logs correctly. I was having minor problems with stopping tracelog process.
[tracelog-logs-210822.zip](https://github.com/vadimgrn/usbip-win2/files/9388870/tracelog-logs-210822.zip)

Main difference about this version is few seconds after I attach the device the explorer window shows, but it's blank and then IO error message pops up.

**Comment by vadimgrn** [comment]
ESHUTDOWN is returned for clear endpoint halt that sends after EPIPE. The [description](https://docs.kernel.org/driver-api/usb/error-codes.html) of this error is
`The device or host controller has been disabled due to some problem that could not be worked around, such as a physical disconnect.
`

**Comment by vadimgrn** [comment]
It's hard to fix this error without having the device.

**Comment by tadabrowski** [comment]
I think I still own another Kindle. The screen is broken so it's completely unusable, but everything other works normally. It's an older version, but I bet problems are the same - I will check it.

Maybe I could send it to you?

**Comment by vadimgrn** [comment]
Thank you, but if you are in USA, I am on another side of the globe :)

**Comment by tadabrowski** [comment]
Naaaah. Probably I'm much closer than you think. I'm in Poland.

**Comment by vadimgrn** [comment]
I am in Ukraine. You can send it, but I can't guarantee that I will manage to fix this issue.

**Comment by Ouch-call** [comment]
Have the above issues been resolved? I am having similar problems now, I was running usbip server on ubuntu1804 (with a uvc webcam inserted into it) and then windows as a client; But as soon as attach is attached on the pc, Device Manager keeps showing pop-up disconnections, and so on.Nor can it be uninstall at this time. Because it BSOD. I've tried both ude and wdm, and it's always like this。But ubuntu will work just fine with a USB flash drive. Does usbip not support uvc webcam yet?

**Comment by vadimgrn** [comment]
It works with webcams that I have. You could post output from WinDbg for BSOD.

**Comment by vadimgrn** [comment]
You should use the latest release 0.9.3.2

**Comment by Ouch-call** [comment]
Thanks!! This version is at least recognized as a uvc device in the device manager。However, I used a uvc test tool to test an image and the ubuntu kernel reported an error。In addition, the installation program reported a lot of "Trojan virus", and also need to open the win10 test mode。

`Dec  3 23:14:14 ouch kernel: [10364.298092] g_webcam gadget: uvc_function_set_alt(1, 1)
Dec  3 23:14:14 ouch kernel: [10364.298096] g_webcam gadget: reset UVC
Dec  3 23:14:14 ouch kernel: [10364.302551] use of bytesused == 0 is deprecated and will be removed in the future,
Dec  3 23:14:14 ouch kernel: [10364.302553] use the actual size instead.
Dec  3 23:14:14 ouch kernel: [10364.562037] g_webcam gadget: uvc_function_set_alt(1, 0)
Dec  3 23:14:14 ouch kernel: [10364.562042] VS request cancelled.
Dec  3 23:14:14 ouch kernel: [10364.562056] VS request cancelled.
Dec  3 23:14:14 ouch kernel: [10364.562056] VS request cancelled.
Dec  3 23:14:14 ouch kernel: [10364.562057] VS request cancelled.
Dec  3 23:14:14 ouch kernel: [10364.608283] BUG: unable to handle kernel NULL pointer dereference at 0000000000000360
Dec  3 23:14:14 ouch kernel: [10364.608321] IP: vep_dequeue+0x1b/0xd0 [usbip_vudc]
Dec  3 23:14:14 ouch kernel: [10364.608323] PGD 0 P4D 0 
Dec  3 23:14:14 ouch kernel: [10364.608327] Oops: 0000 [#1] SMP PTI
Dec  3 23:14:14 ouch kernel: [10364.608356] Modules linked in: g_webcam(OE) usb_f_uvc videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core videodev media libcomposite usbip_vudc usbip_core udc_core isofs rfcomm cpuid btrfs zstd_compress xor raid6_pq ufs qnx4 hfsplus hfs minix ntfs msdos jfs xfs libcrc32c vmw_vsock_vmci_transport vsock bnep binfmt_misc crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel snd_ens1371 aes_x86_64 snd_ac97_codec gameport ac97_bus snd_pcm crypto_simd glue_helper snd_seq_midi snd_seq_midi_event cryptd snd_rawmidi snd_seq vmw_balloon btusb intel_rapl_perf btrtl btbcm input_leds joydev snd_seq_device snd_timer serio_raw btintel snd bluetooth ecdh_generic vmwgfx ttm soundcore drm_kms_helper shpchp drm fb_sys_fops syscopyarea sysfillrect sysimgblt vmw_vmci mac_hid sch_fq_codel nfsd
Dec  3 23:14:14 ouch kernel: [10364.613996]  auth_rpcgss nfs_acl parport_pc lockd ppdev grace sunrpc lp parport ip_tables x_tables autofs4 hid_generic usbhid hid psmouse ahci libahci mptspi mptscsih e1000 mptbase scsi_transport_spi i2c_piix4 pata_acpi
Dec  3 23:14:14 ouch kernel: [10364.614286] CPU: 1 PID: 14309 Comm: uvc-gadget Tainted: G           OE    4.15.0-197-generic #208-Ubuntu
Dec  3 23:14:14 ouch kernel: [10364.614289] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 07/29/2019
Dec  3 23:14:14 ouch kernel: [10364.614297] RIP: 0010:vep_dequeue+0x1b/0xd0 [usbip_vudc]
Dec  3 23:14:14 ouch kernel: [10364.614299] RSP: 0018:ffffacf5846afbe0 EFLAGS: 00010282
Dec  3 23:14:14 ouch kernel: [10364.614301] RAX: 0000000000000000 RBX: ffff8bf987293710 RCX: ffff8bf987293000
Dec  3 23:14:14 ouch kernel: [10364.614303] RDX: 0000000000000002 RSI: ffff8bf9c06c3380 RDI: ffff8bf9f407a200
Dec  3 23:14:14 ouch kernel: [10364.614305] RBP: ffffacf5846afc08 R08: ffff8bf9894f6f00 R09: ffff8bf987293000
Dec  3 23:14:14 ouch kernel: [10364.614306] R10: ffff8bf98564f8c0 R11: ffff8bf98564f8c0 R12: ffff8bf9f407a200
Dec  3 23:14:14 ouch kernel: [10364.614307] R13: ffff8bf9c06c3380 R14: ffff8bf987293778 R15: ffff8bf9894f6f00
Dec  3 23:14:14 ouch kernel: [10364.614310] FS:  00007f00d390b500(0000) GS:ffff8bf9fb640000(0000) knlGS:0000000000000000
Dec  3 23:14:14 ouch kernel: [10364.614311] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Dec  3 23:14:14 ouch kernel: [10364.614312] CR2: 0000000000000360 CR3: 000000002a2c0005 CR4: 00000000003606e0
Dec  3 23:14:14 ouch kernel: [10364.614347] Call Trace:
Dec  3 23:14:14 ouch kernel: [10364.614411]  ? usb_ep_dequeue+0x23/0x90 [udc_core]
Dec  3 23:14:14 ouch kernel: [10364.614495]  uvcg_video_enable+0x47/0x1e0 [usb_f_uvc]
Dec  3 23:14:14 ouch kernel: [10364.614502]  ? uvcg_dequeue_buffer+0x16/0x20 [usb_f_uvc]
Dec  3 23:14:14 ouch kernel: [10364.614507]  uvc_v4l2_streamoff+0x33/0x40 [usb_f_uvc]
Dec  3 23:14:14 ouch kernel: [10364.614542]  v4l_streamoff+0x20/0x30 [videodev]
Dec  3 23:14:14 ouch kernel: [10364.614550]  __video_do_ioctl+0x370/0x380 [videodev]
Dec  3 23:14:14 ouch kernel: [10364.614557]  video_usercopy+0x26e/0x670 [videodev]
Dec  3 23:14:14 ouch kernel: [10364.614563]  ? video_ioctl2+0x20/0x20 [videodev]
Dec  3 23:14:14 ouch kernel: [10364.614569]  video_ioctl2+0x15/0x20 [videodev]
Dec  3 23:14:14 ouch kernel: [10364.614575]  v4l2_ioctl+0x84/0xf0 [videodev]
Dec  3 23:14:14 ouch kernel: [10364.614728]  do_vfs_ioctl+0xa8/0x630
Dec  3 23:14:14 ouch kernel: [10364.614735]  SyS_ioctl+0x79/0x90
Dec  3 23:14:14 ouch kernel: [10364.614788]  do_syscall_64+0x73/0x130
Dec  3 23:14:14 ouch kernel: [10364.614793]  entry_SYSCALL_64_after_hwframe+0x41/0xa6
Dec  3 23:14:14 ouch kernel: [10364.628926] RIP: 0033:0x7f00d3422217
Dec  3 23:14:14 ouch kernel: [10364.628932] RSP: 002b:00007fff55efba38 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
Dec  3 23:14:14 ouch kernel: [10364.628936] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007f00d3422217
Dec  3 23:14:14 ouch kernel: [10364.628937] RDX: 00007fff55efba50 RSI: 0000000040045613 RDI: 0000000000000003
Dec  3 23:14:14 ouch kernel: [10364.628939] RBP: 00007fff55efba70 R08: 0000000000000000 R09: 0000000000000000
Dec  3 23:14:14 ouch kernel: [10364.628940] R10: 00007fff55efbd20 R11: 0000000000000246 R12: 0000557165f4dc10
Dec  3 23:14:14 ouch kernel: [10364.628942] R13: 00007fff55efbff0 R14: 0000000000000000 R15: 0000000000000000
Dec  3 23:14:14 ouch kernel: [10364.628946] Code: 5d 41 5e 5d c3 b8 ea ff ff ff eb f0 0f 1f 40 00 0f 1f 44 00 00 48 85 ff 0f 84 b4 00 00 00 48 85 f6 0f 84 ab 00 00 00 48 8b 46 58 <48> 83 b8 60 03 00 00 00 0f 84 9f 00 00 00 55 48 89 e5 41 55 4c 
Dec  3 23:14:14 ouch kernel: [10364.628973] RIP: vep_dequeue+0x1b/0xd0 [usbip_vudc] RSP: ffffacf5846afbe0
Dec  3 23:14:14 ouch kernel: [10364.628974] CR2: 0000000000000360
Dec  3 23:14:14 ouch kernel: [10364.629019] ---[ end trace e7ee96d60c0a505b ]---
Dec  3 23:14:14 ouch kernel: [10364.642234] usbip_vudc: v_rx exit with error -32
Dec  3 23:14:14 ouch kernel: [10364.657657] g_webcam gadget: uvc_function_disable`

**Comment by Ouch-call** [comment]
win10detach fails when ubuntu fails, but the usbip.exe port will still be able to see the device

C:\Users\Administrator\Desktop\11>usbip.exe detach -p 01
usbip: error: failed to detach

**Comment by vadimgrn** [comment]
I can do nothing without driver log

**Comment by vadimgrn** [comment]
UDE driver should work
