### ISSUE TITLE
Example USB IP server

### ISSUE THREAD

**Issue by nitzanfarhi** [vadimgrn/usbip-win2#22]
Hey,
Do you have any reccomendations for usb ip servers that can be used to emulate usb devices?
[https://github.com/smulikHakipod/USB-Emulation](https://github.com/smulikHakipod/USB-Emulation) and all it's forks do not work.

**Comment by vadimgrn** [comment]
Hi, try https://github.com/dorssel/usbipd-win

**Comment by nitzanfarhi** [comment]
Does this repo also alow emulating devices? It seems like it just transfers recieved usb packets over ip

**Comment by nitzanfarhi** [comment]
I'm looking for a usbip server that emulates usb devices

**Comment by vadimgrn** [comment]
usbip server emulates nothing, it's the function of usbip client.
