### ISSUE TITLE
Followed instructions to install USBIP server, got an error when listing USB devices

### ISSUE THREAD

**Issue by Manic137** [vadimgrn/usbip-win2#26]
This is the error: 
usbip: error: failed to open /usr/share/hwdata//usb.ids
 - busid 2-1.7 (054c:05c5)
   unknown vendor : unknown product (054c:05c5)

**Comment by Manic137** [comment]
Update, found different instructions online and managed to install USBIP and followed instruction server side, but now client side is having issues, error: vhci driver is not loaded

**Comment by Manic137** [comment]
Never mind, I am an idiot, restarted pc and it works now

**Comment by noah-hwang** [comment]
@Manic137 
hello
Can you share how you dealt with this problem
I encountered the same issues, error: vhci driver is not loaded
