### ISSUE TITLE
Drive unloading

### ISSUE THREAD

**Issue by Lyxing-star** [vadimgrn/usbip-win2#31]
Hello, when a device is created in the bus driver and the device is in use, and the bus driver is directly unloaded in the device manager, how do you ensure resource release?

**Comment by vadimgrn** [comment]
Hello, during the unloading of the driver it destroys all devices. DriverVerifier and WdfVerifier are used to make sure this is true.

**Comment by Lyxing-star** [comment]
Hello, what is the first event triggered when unloading the bus driver in the device manager? To ensure that the unhandled url messages can be processed and the driver can be unloaded normally

**Comment by vadimgrn** [comment]
Develop branch, drivers/ude/vhci.cpp, create_vhci, vhci_cleanup

**Comment by Lyxing-star** [comment]
> Develop branch, drivers/ude/vhci.cpp, create_vhci, vhci_cleanup

thankyou

**Comment by Lyxing-star** [comment]
> 您好，在设备管理器中卸载总线驱动程序时触发的第一个事件是什么？确保可以处理未处理的 url 消息并且可以正常卸载驱动程序



> > 开发分支、驱动程序/ude/vhci.cpp、create_vhci vhci_cleanup
> 
> 谢谢

My test found that if you do not actively unplug the device after inserting the device and unload the driver in the device manager, you cannot call vhci_ Clean, do you know which event is triggered first when the driver is unloaded in the device manager?

**Comment by vadimgrn** [comment]
I gave you the complete answer. I do not call vhci_cleanup at all.
WDF_OBJECT_ATTRIBUTES.EvtCleanupCallback = vhci_cleanup;
The kernel calls this callback for WDFDEVICE. You should look in driver's log to clarify what is going on when the driver is unloading.

**Comment by Lyxing-star** [comment]
> I gave you the complete answer. I do not call vhci_cleanup at all. WDF_OBJECT_ATTRIBUTES.EvtCleanupCallback = vhci_cleanup; The kernel calls this callback for WDFDEVICE. You should look in driver's log to clarify what is going on when the driver is unloading.

ok，thankyou，I haven't found any event triggered so I want to ask you

**Comment by Lyxing-star** [comment]
Hello, please ask me again. After I plug in the USB device now, it will be displayed in the device manager according to the name I set. After I call plugout, the device will be pulled out. When I plug in the same port again, the name displayed on the device will still be the same, not the new name. Do you know how to solve this problem?

**Comment by vadimgrn** [comment]
Hello, I don't know. May be it worth add ability to assign FriendlyName for a remote device in command "usbip attach".
