### ISSUE TITLE
Multiple bug &  "low speed"

### ISSUE THREAD

**Issue by DzzD** [vadimgrn/usbip-win2#37]
Hello I have tried the last three version : 
- 9.5.2 : usbip with or without parameters command output nothing
- 9.3.4 : EDIT: works but still low speed for a webcam
- 9.3.3 : usbip can list and attach but use "low speed" on USB cam where before it was using "fulll speed"

Let's try 9.3.2 !

**Comment by vadimgrn** [comment]
> * usbip with or without parameters command output nothing

I don't get it. Use --debug option. Empty output is OK if nothing to output.

**Comment by DzzD** [comment]
wait, I unistall/reinstall (i try multiple version)

**Comment by DzzD** [comment]
I mean this : 

![image](https://user-images.githubusercontent.com/12198339/235364920-acb11d31-e983-4004-b95d-7ffa29853225.png)

**Comment by DzzD** [comment]
this happen with the latest version 9.5.2 (9.3.4 works, but still use low speed where it should not)

**Comment by DzzD** [comment]
Ok installing the debug version I got this : 
![image](https://user-images.githubusercontent.com/12198339/235365153-69ca13aa-014e-458e-bc78-e87d5ea90fca.png)

this explain why the release version did not output anything to the console

**Comment by vadimgrn** [comment]
I'll check it tomorrow, thank you.

**Comment by DzzD** [comment]
For information, if it can help, with the previous version (9.3.3) I got : 

![image](https://user-images.githubusercontent.com/12198339/235365647-e9fbc136-65c3-41ab-9674-9beaf2419476.png)

Thanks to you !

**Comment by DzzD** [comment]
Some more informations : 
With the version 9.3.3 I managed to make it works at full speed, it seems there is a maybe a mess between the two drivers, dont know.

If I deactivate xhci driver I fot error on usbip pot, but my camera is working well, I can use it maximum resolution.

![image](https://user-images.githubusercontent.com/12198339/235367120-2e7368ce-ff22-4aad-a287-aa9c40e15c81.png)

**Comment by vadimgrn** [comment]
When 0.9.3.X and 0.9.5.X are installed, make sure that you are calling right usbip.exe. It is binary incompatibility. I checked the latest release, all is OK.

**Comment by DzzD** [comment]
I always unsinstall the previous version, I use the one that come with the installer is that ok ?

**Comment by DzzD** [comment]
Re-tested, same, uninstall/reinstall and I got : 
![image](https://user-images.githubusercontent.com/12198339/235434414-e45fc269-2096-41c6-a58f-482db96f1a34.png)

**Comment by DzzD** [comment]
Another question, why some device appear in "low speed" ? 

They was working well before, but now they are set as low speed

![image](https://user-images.githubusercontent.com/12198339/235437876-48836cae-5a7d-41cb-abea-8505ccb6ec93.png)

**Comment by vadimgrn** [comment]
You should completely uninstall all usbip drivers. You should do it manually as described in readme.

**Comment by DzzD** [comment]
Well I ll try, in the meantime I have found a cheap software that works well for me and wich look stable (wich shows that you have great potential to sell this one once packager & reliable)

**Comment by vadimgrn** [comment]
I am not aware about commercial usbip implementations for Windows.

**Comment by DzzD** [comment]
I just tried Virtualhere, it works flawlessly for me : 

![image](https://user-images.githubusercontent.com/12198339/235479666-3b099787-6e1e-4fa4-bc12-8aed3ffb9886.png)

I have virtualised three USB of a raspberrypi3 to control my laser from lightburn (+ a controle camera) using WIFI. 

Everything works perfectly, it is free for one USB over IP on a device and 50$ for unlimited (I have bought their license)

**Comment by DzzD** [comment]
It use it own server (server installation requiere only one line, and is finished in less than 30s on raspberry)

Client side everything is in a single program.

Full server/client installation took less than 5 minutes.

**Comment by vadimgrn** [comment]
There are a lot of proprietary solutions for sharing USB devices. VirtualHere is one of them, it can't work with Linux usbip server.

**Comment by DzzD** [comment]
Actually, I would have prefer to use your solution as it is open source and already pretty advanced, but for now Virtualhere do the job very well and very reliabily without requiring windows test mode. I will keep an eye here. Keep up the good work !
