### ISSUE TITLE
UDE: BSOD on ConcurrencyCheck Deletion

### ISSUE THREAD

**Issue by nraggett** [vadimgrn/usbip-win2#40]
Looks like the assertion for concurrency failed on deletion. BSOD dump is attached below:
[BSOD Dump](https://github.com/vadimgrn/usbip-win2/files/11588753/concurrency_check_assertion.log)

Additional info: \
This is running with a USB device sending 1000hz packets. The sheer number of packets coming through could be the cause. Replicated with a Tundra Tracker and running Libsurvive.

**Comment by vadimgrn** [comment]
SynchronizationScope can't be set for UDECXUSBENDPOINT. EvtUsbEndpointPurge is called concurrently with IRP_MJ_INTERNAL_DEVICE_CONTROL, both are call WskSend.

**Comment by vadimgrn** [comment]
I can't even protect WskSend by KSPIN_LOCK. It seems it might be called on DIRQL (higher than DISPATCH_LEVEL) from such callbacks as endpoint_purge. I need more time to fix that.

**Comment by vadimgrn** [comment]
Fixed in 0.9.5.3

**Comment by nraggett** [comment]
Thanks Vadym! It works well on my setup.
