### ISSUE TITLE
Windows server 2019 support

### ISSUE THREAD

**Issue by srdimitroff** [vadimgrn/usbip-win2#42]
Interested installing this on a VM running Windows Server 2019 edition. When I try running the installer it says that "This Program does not support the version of windows your computer is running" 

Windows Server 2019 is more or less similar enough to Windows 10/11. Thanks!

**Comment by vadimgrn** [comment]
What exact version of Windows?

**Comment by srdimitroff** [comment]
Thanks for the quick reply. Under windows edition names it:

Windows Server 2019 Standard

**Comment by vadimgrn** [comment]
It should be like 
Windows 10 Version 2004 (OS build 19041). I use API that is available since that release for Win10.

**Comment by srdimitroff** [comment]
Yeah I thought it should be similar to that with Server 2019, however the .exe to install it will not start due to  the error:

"This program does not support the version of Windows your computer is running."

![Screenshot 2023-06-28 090601](https://github.com/vadimgrn/usbip-win2/assets/46541600/7d5fba49-52b1-4f95-b459-a1ba42259177)

**Comment by vadimgrn** [comment]
I see, but I want you to get full version info about your Win Server. It contains version and OS build numbers. Win Server 2019 is not enough, I suppose.

**Comment by vadimgrn** [comment]
It seems so. It's possible to replace ExAllocatePool2 as described [here](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2). If you are a programmer, you could do that.

**Comment by vadimgrn** [comment]
There are several places where Win version should be changed as well.
![Screenshot 2023-06-29 090530](https://github.com/vadimgrn/usbip-win2/assets/67631045/e4983589-46d5-40cb-a591-611adae589be)
![Screenshot 2023-06-29 090555](https://github.com/vadimgrn/usbip-win2/assets/67631045/abeeff25-eba0-4dbd-9c6c-418e5cc5d660)
![Screenshot 2023-06-29 090642](https://github.com/vadimgrn/usbip-win2/assets/67631045/2abc8292-1362-4c6e-ae76-966d36e08d78)

**Comment by vadimgrn** [comment]
It won't be so easy. There are some other functions that available since Windows 10, version 2004. For example, RtlUTF8StringToUnicodeString and RtlInitUTF8String.

**Comment by vadimgrn** [comment]
I did it :) It should run on Windows 10 x64 Version 1709(OS build 16299) and later.
Could you build master branch and try it, please?

**Comment by srdimitroff** [comment]
Awesome work, I appreciate this! I did end up building it from the master last night and was having some issues with the drivers after the installation. I tried your build and it was doing the same. When I install it, the USBip 3.X Emulated Host Controller driver installs but says:

"Windows cannot start this hardware device because its configuration information (in the registry) is incomplete or damaged. (Code 19)"

![Screenshot 2023-07-02 080040](https://github.com/vadimgrn/usbip-win2/assets/46541600/1d616959-f984-4a36-a5e5-5c3fdba717c5)


![Screenshot 2023-07-02 080211](https://github.com/vadimgrn/usbip-win2/assets/46541600/94c16abe-15ff-4571-a92d-12ec4d7258d1)

So I tried restarting the VM and then all the USB controllers have that same error message:


![Screenshot 2023-07-02 080158](https://github.com/vadimgrn/usbip-win2/assets/46541600/b779bb15-8ef5-4eb9-8fd5-9fd8a78c49a1)

I am currently testing it out on Win10 LTSC version 1809 build 17763.3887 which will be similar to the Windows Server 2019 I eventually want to run it on.

**Comment by vadimgrn** [comment]
I don't have Win10 to test. Collect logs, pls.

**Comment by srdimitroff** [comment]
Which logs can I provide? I ran the verifier for the driver and can provide that?

**Comment by vadimgrn** [comment]
Today I installed Win10 1709 on VM. There are issues with .inf files for drivers. Other than that "pnputil /remove-device" available starting in Windows 10 version 2004. Errors for .inf files are very generic, it is not possible to understand what exactly wrong. I'm going to move these changes to a new branch, master branch will be reverted to Win 10 2004.

**Comment by vadimgrn** [comment]
https://github.com/vadimgrn/usbip-win2/tree/win10_1709

**Comment by srdimitroff** [comment]
Does the driver need that "pnputil /remove-device" to run properly? I'm not sure if that is only needed when uninstalling the driver or is it for detaching usbip device?

**Comment by vadimgrn** [comment]
It is required during the uninstallation.

**Comment by vadimgrn** [comment]
I found the solution, downgrade of Win version will be implemented in develop branch soon.

**Comment by vadimgrn** [comment]
The branch [win10_1809](https://github.com/vadimgrn/usbip-win2/tree/win10_1809) is completed, usbip can be installed/removed correctly. I'm thinking if it worth to merge this branch into develop.

The only issue is that usbip2_ude service remains in registry after the uninstallation on Win10 1809, but it is harmless.

**Comment by vadimgrn** [comment]
The branch has merged into develop.
