### ISSUE TITLE
Supported device addition for Wiki

### ISSUE THREAD

**Issue by TheFiZi** [vadimgrn/usbip-win2#44]
I can't submit a edit to the wiki page for supported devices.

Just wanted to add one:

- Apple
  - iPhone 13 Pro, iOS 17.0.1

I've got the iPhone connected to a Windows 11 machine, shared over IP to a Server 2019 machine. I was able to interact with the iPhone using iMazing, approve trusting the device, pull a backup and view data on the phone.

Server 2019: [usbip-win2 UDE 0.9.5.6](https://github.com/vadimgrn/usbip-win2/releases/tag/v.0.9.5.6)
Windows 11: usbipd-win 3.2.0

**Comment by vadimgrn** [comment]
Thank you very much for the feedback! I've added iPhone 13 Pro to the list.
