### ISSUE TITLE
bsod when trying to forward smart card or yubikey

### ISSUE THREAD

**Issue by paweljasinski** [vadimgrn/usbip-win2#45]
Hi,

I have tried the following combinations. In all cases trying to connect smartcard reader or yubikey triggers bsod in windows client.

Status  Server      Client               Device
-------------------------------------------------------------------
bsod    Android    Windows          Omnikey Smart Card Reader
bsod    Android    Windows          Yubikey
bsod    Linux        Windows          Yubikey
ok        Linux        Windows          Mac keyboard
ok        Android    Linux                Yubikey
ok        Linux        Linux                Yubikey

Cheers
--pawel

**Comment by vadimgrn** [comment]
https://github.com/vadimgrn/usbip-win2/tree/develop#debugging-bsod

**Comment by vadimgrn** [comment]
Crash log is missing
