### ISSUE TITLE
can you remove testsigning after installing winusb?

### ISSUE THREAD

**Issue by comsyspro** [vadimgrn/usbip-win2#48]
is it possible to disable testsigning with `bcdedit.exe /set testsigning off` after you have installed winusb with the test certificates? is this possible for both ude and wdm driver releases or only for ude?

**Comment by vadimgrn** [comment]
You can (disable)[https://github.com/vadimgrn/usbip-win2#disable-windows-test-signing-mode-without-removing-usbip] test signing, but usbip will not work until it will be enabled.

**Comment by comsyspro** [comment]
yes, i did try that and also deleted the UpperFilters value in the registry. after rebooting you get a yellow warning mark on "usbip root" and USBip 3.X" in device manager and usbip is out of function. what would it cost to get a signed driver?

**Comment by vadimgrn** [comment]
https://github.com/vadimgrn/usbip-win2/issues/13

**Comment by Oleszkiewicz** [comment]
Hi, if the problem is the business entity - I can help with that, I have a company in Poland that is already a Microsoft partner, Provided we get funding for the cert I can go through EV code signing validation. From what I see it is possible to get one from Comodo a bit south of USD 900 or I can get one locally from Certum at approx USD 1050 for 3 years.

**Comment by vadimgrn** [comment]
Hi, it would be nice.

**Comment by Oleszkiewicz** [comment]
So how would we proceed ?

**Comment by vadimgrn** [comment]
Sorry, I'm busy right now.I'll answer later.

**Comment by vadimgrn** [comment]
So the question of money to buy an EV certificate?

**Comment by Oleszkiewicz** [comment]
yup, I can donate my time to go through the certification process, recompile and sign, but no possibility to fund this from the company right now.

**Comment by vadimgrn** [comment]
Donations have been very rare in recent months, I don't even remember the last time. I don't want to spend my own money for that during the war.

**Comment by Oleszkiewicz** [comment]
Sure , I don’t expect that, is there actually a possibility to set some kind of a goal on github or somewhere else? Are you safe in the war?

**Comment by comsyspro** [comment]
what is the actual best offer for a 3 three year driver certificate? could you create a kickstarter project https://www.kickstarter.com/ to collect money?

**Comment by vadimgrn** [comment]
There are two options to sponsor this project, the third is not required.

**Comment by comsyspro** [comment]
i mentioned kickstarter as you can see how much is already collected and you can define a timespan for collecting the reuired money. at the moment you can not know how much money is collected from some interested people and you can't know when the certificate will be ready. so can you publish this somehow or with such a platform like kickstarter.

**Comment by eebssk1** [comment]
Maybe ask https://about.signpath.io/product/open-source ?

**Comment by fredemmott** [comment]
SignPath's open source offering does not include EV certificates, so isn't useful here.

**Comment by FirstS0ul** [comment]
How is the Status and how can i donate? :-)

**Comment by vadimgrn** [comment]
![Screenshot from 2024-10-25 11-54-47](https://github.com/user-attachments/assets/e8fbbd57-1e71-418f-aa05-958c6445e830)
