### ISSUE TITLE
How can i sign driver?

### ISSUE THREAD

**Issue by Kobain-Seo** [vadimgrn/usbip-win2#51]
Hi, I recently purchased EV code signing certificate for personal purpose. I'd like to sign the latest release but i don't know how. 

is there any guide for it?

**Comment by vadimgrn** [comment]
Hi, I don't know how to do that.

**Comment by Kobain-Seo** [comment]
I tried to sign drivers properly but it didn't work. Since they are kernel driver, it is not matter of certificate. I have to register to Microsoft as hardware developer. It is complicated and takes long.
