### ISSUE TITLE
Windows blue screen when I attach the Thrustmaster T150

### ISSUE THREAD

**Issue by constantindjonkam** [vadimgrn/usbip-win2#53]
In attempting to attach a Thrustmaster T150 steering wheel, my windows 11 client crashes (blue screen) every time. What could eventually be causing this?

**Comment by vadimgrn** [comment]
https://en.wikipedia.org/wiki/Blue_screen_of_death

**Comment by constantindjonkam** [comment]
while debugging the BSOD issue the T150 seemed to work now. I guess something went wrong during the installation(I uninstalled it after facing BSOD. Reinstalling doesn't cause BSOD anymore) or the fact that I installed the debugging programs helped. I will provide the logs if I face the issue again

**Comment by vadimgrn** [comment]
Good news, thank you!
