### ISSUE TITLE
Logs don't show up in cmd, only Powershell

### ISSUE THREAD

**Issue by brandonros** [vadimgrn/usbip-win2#56]
![image](https://github.com/vadimgrn/usbip-win2/assets/8949910/2b84e299-12d6-42f7-9e60-5f5f632a0996)

**Comment by vadimgrn** [comment]
This bug has fixed in master branch. I'll public a new release tomorrow.

**Comment by brandonros** [comment]
I am working on getting logs by the way for the other issue, appreciate you.
