### ISSUE TITLE
tcp-port is bypassed

### ISSUE THREAD

**Issue by knavels** [vadimgrn/usbip-win2#6]
Hello @vadimgrn 

I was testing your fork of windows client and I did the following scenario and it didn't work, seems the client ignores the tcp-port

* create ssh tunnel for localhost:3000 to [IPV6 of the device]:3240
* run `uspip.exe list- r localhost --tcp-port 3000`
* got `usbip: error: failed to connect a remote host: localhost`
* kill tunnel
* create new tunnel from 3240 of localhost to 3240 of device's IPV6
* run `usbip.exe list -r localhost`
* it works

Can you check what's the problem with tcp-port?

**Comment by vadimgrn** [comment]
The usbip utility is the same as in the original repo. I will fix this bug later, now I'm working on other feature.

**Comment by vadimgrn** [comment]
--tcp-port is a global option, but you passes it as option of "list" command. The issue is that "list" doesn't return error for unknown option.
This works
uspip.exe --tcp-port 3000 list -r localhost
