### ISSUE TITLE
Usbip server

### ISSUE THREAD

**Issue by GreatAg** [vadimgrn/usbip-win2#63]
Hi, Do you have any plan to provide server support for usbip in windows?
Thanks

**Comment by vadimgrn** [comment]
Hi, there is no such plan. I could write it, but I don't have a desire to do that. Maybe I will change my mind in the future.

**Comment by GreatAg** [comment]
Thanks for quick reply. what about GUI? do you have any plan around it?

**Comment by vadimgrn** [comment]
GUI will be included in the next release in this month.

**Comment by GreatAg** [comment]
Hi again, i want to know that do you have any plan to support secure connection for this project?

**Comment by GreatAg** [comment]
But tools like usb over network or usb network gate supports secure connection. what is the difference? they are using another protocol?

**Comment by vadimgrn** [comment]
These proprietary software use its own protocol. USBip is based on [this](https://www.kernel.org/doc/html/latest/usb/usbip_protocol.html)

**Comment by GreatAg** [comment]
Thanks for your quick reply.
Does BSOD problem will be resolved in the next release?
and another question is when i installed the usbip-win2.exe does it automatically install wdm and ude driver?

**Comment by vadimgrn** [comment]
What BSOD? Read the description of the project, pls.

**Comment by GreatAg** [comment]
The description said: Is not ready for production use, can cause BSOD!

**Comment by vadimgrn** [comment]
Every driver can cause BSOD. Just try it with your devices.

**Comment by vadimgrn** [comment]
WMD https://github.com/vadimgrn/usbip-win2/releases/tag/wdm-0.9.3.4

**Comment by GreatAg** [comment]
Is the exact release date of the new version known? I am very keen on the GUI.

**Comment by vadimgrn** [comment]
Try it now https://drive.google.com/file/d/11fBl7tv00tMZhsGdYuuqV14ic94JYBz_/view?usp=drive_link

**Comment by GreatAg** [comment]
Thank you for your efforts and sharing new release with me.
I did a preliminary review and here are my thoughts:
1- when i enter a wrong ip address which doesn't have any usbip client on it the app goes into not responding as follow:
![Screenshot from 2024-03-13 08-05-36](https://github.com/vadimgrn/usbip-win2/assets/85877807/2622d579-3572-44cc-bccd-1842c7249a41)

2- It would be nicer if the reload button refresh the all devices in all of my servers rather than just reloading the attached devices and only show them.

3. I think load and save are useless. What are they used for?

4. It would be nicer that when i close the app, it runs in background and the hidden apps how the app icons.

I will look into it further and keep you posted on my comments. Thanks.

**Comment by vadimgrn** [comment]
> 1. When i enter a wrong ip address which doesn't have any usbip client on it the app goes into not responding as follow:
This is unavoidable because the call to the driver is blocking an cannot be cancelled.

> 2\. It would be nicer if the reload button refresh the all devices in all of my servers rather than just reloading the attached devices and only shows them.

Not sure about that. It allows you to remove all unused devices from the tree. Ctrl+R and Ctrl+L do what you want.


> 3\. I think load and save are useless. What are they used for?

They are useful if you try use it.

> 4\. It would be nicer that when i close the app, it runs in the background and the hidden apps shows the app icons.

Not in this release.


> Another question i have is that the wmd version supports the gui when it published?

WDM driver is obsolete and will be completely abandoned after this release.

**Comment by GreatAg** [comment]
> > 1. When i enter a wrong ip address which doesn't have any usbip client on it the app goes into not responding as follow:
> 
> This is unavoidable because the call to the driver is blocking and cannot be cancelled.
> 
> > 2. It would be nicer if the reload button refresh the all devices in all of my servers rather than just reloading the attached devices and only shows them.
> 
> Not sure about that. It allows you to remove all unused devices from the tree. Ctrl+R and Ctrl+L do what you want. Something like 'Refresh' is not required at all, the app updates its state by reading status events from the driver.
> 
> > 3. I think load and save are useless. What are they used for?
> 
> They are useful if you use it :) Load will be executed during the app start if you save something, otherwise you must always add devices each time.
> Wow I didn't know that, I tested it and it works, this is a nice idea, Thanks.
> > 4. It would be nicer that when i close the app, it runs in the background and the hidden apps shows the app icons.
> 
> Not in this release.
> 
> > Another question i have is that the wmd version supports the gui when it published?
> 
> WDM driver is obsolete and will be completely abandoned after this release.
> Does ude driver is stable and fully functional?

**Comment by GreatAg** [comment]
>> They are useful if you use it :) Load will be executed during the app start if you save something, otherwise you must always add devices each time.
>
> Wow I didn't know that, I tested it and it works, this is a nice idea, Thanks.

>> WDM driver is obsolete and will be completely abandoned after this release.
>
> Does ude driver is stable and fully functional?

**Comment by GreatAg** [comment]
Since i install new release when i attach a webcam to my windows after sometime my windows gets freeze. I didn't see this issue with the current version!
is there something wrong with the driver?

**Comment by vadimgrn** [comment]
There were no changes in the driver since previous release, as I remember.

**Comment by GreatAg** [comment]
Ok, i reinstalled it and the problem gone.

**Comment by GreatAg** [comment]
Hi, what is SDK and how can i use it? does it have any manual?

**Comment by vadimgrn** [comment]
Look in libusbip [headers](https://github.com/vadimgrn/usbip-win2/tree/develop/userspace/libusbip), all function have documented.

**Comment by GreatAg** [comment]
I am still experiencing freezing in my windows. Any idea?

**Comment by GreatAg** [comment]
Hi, i have some issue in building project.
I build it in visual studio in following procedures:
1- i open usbip_win2.sln file then right click on package and then set Driver Signing to usbip.pfx and there is nowhere i can enter the password
2- I build it and the files is available under the Release folder but the .exe rapidly opens and close as a black cmd

I want an installation exe file. what should i do? can you share detail procedures of getting relase .exe file from the project?
