### ISSUE TITLE
Windows Freezing

### ISSUE THREAD

**Issue by GreatAg** [vadimgrn/usbip-win2#64]
Hi, i experience freezing with microphone device. Here is the scenario:
I attach the microphone device into my windows then i open mictest.com website to test my microphone, everything goes well until i stop the microphone or exit the website. as soon as i click on stop or exit button my windows gets freeze. 
Can i provide you more details to address the issue and resolve it?

**Comment by vadimgrn** [comment]
https://github.com/vadimgrn/usbip-win2/tree/develop?tab=readme-ov-file#obtaining-usbip-logs-on-windows
