### ISSUE TITLE
Android server ?

### ISSUE THREAD

**Issue by moi952** [vadimgrn/usbip-win2#67]
Hi,
I want to use this tool but I am looking for a usbip server for android (android 11)

Are any available?
Thanks

**Comment by vadimgrn** [comment]
Hi, I am not aware of any Android USBIP server, either open source or commercial.

**Comment by moi952** [comment]
Ah too bad, there is virtualHere which is paid and linked to the hardware so if I change my Android box I have to buy a license.

Otherwise there is this https://github.com/cgutman/USBIPServerForAndroid/ but it does not work on my nvidia shield with android 11

Thank you for your answer

**Comment by vadimgrn** [comment]
USBIP server is written on Java, that's weird. The right thing is to build custom kernel.
