### ISSUE TITLE
Could you please fix the audio device bugs in ude mode? 

### ISSUE THREAD

**Issue by zhxin999** [vadimgrn/usbip-win2#68]
I try to attach a usb micphone, but failed. the audio device will be lost after attaching to the client.  Is there any good ideas?

**Comment by vadimgrn** [comment]
This is the most hard issue to solve. I can't manage to fix it yet.

**Comment by vadimgrn** [comment]
The issue has fixed, the next release will be published soon. Some devices still do not work, for example, Apple iPod EarPods with Mic USB-C.

**Comment by vadimgrn** [comment]
EarPods are full speed and they don't work for some other reason, isoch out transfers are successful.

**Comment by bozax** [comment]
Micphone is isoch in transfer.
