### ISSUE TITLE
Disabling "Windows Test Signing Mode" once the program is installed will cause every USB device to stop working

### ISSUE THREAD

**Issue by rogermiranda1000** [vadimgrn/usbip-win2#71]
I had to access with remote controll because I couldn't move my mouse/keyboard (directly connected to the computer)...

### Steps to reproduce

- Follow the install setup
- Run `bcdedit.exe /set testsigning off`
- Restart the PC

**Comment by rogermiranda1000** [comment]
Solved after uninstalling the program; I assume re-enabling testsigning will also work.

**Comment by vadimgrn** [comment]
Obviously it cannot work if test signing is disabled. You can disable it for some reasons without uninstalling usbip. It will work if disable test signing again.

**Comment by rogermiranda1000** [comment]
> it cannot work if test signing is disabled
Special emphasis on the "directly connected to the computer". By disabling that, it almost caused my computer to brick. None of the (directed) connected USBs were recognised, so I couldn't login.

I think this part is worth mentioning, at least...

**Comment by vadimgrn** [comment]
Disable Windows Test Signing Mode without removing USB/IP

usbip2_filter driver must be disabled, otherwise all USB controller

What is wrong? Everything is described.

**Comment by vadimgrn** [comment]
I updated README to emphasize do not set testsigning off when USBip is installed.
