### ISSUE TITLE
can you add manually vendorid and productid of unknown devices?

### ISSUE THREAD

**Issue by comsyspro** [vadimgrn/usbip-win2#73]
i have some usb devices which are not listed in the database for vid and pid pairs. so where can i find these vid and pid list and are these values stored in a file and can you add your own entries for unknown vids and pids? from where usbip is getting these values (from server)?

**Comment by vadimgrn** [comment]
http://www.linux-usb.org/usb-ids.html

**Comment by comsyspro** [comment]
thanks i found it:
[userspace/usbip/usb.ids](https://github.com/vadimgrn/usbip-win2/blob/master/userspace/usbip/usb.ids)

**Comment by vadimgrn** [comment]
This file was downloaded from the site, it is never updated manually.

**Comment by comsyspro** [comment]
ok, then i will append some lines manually.
