### ISSUE TITLE
USB/IP client for windows7/10

### ISSUE THREAD

**Issue by xdlead** [vadimgrn/usbip-win2#76]
I need a USB/IP client that supports Windows7/10, and I can spend money to purchase it

**Comment by vadimgrn** [comment]
Both OS are too old and will not be supported

**Comment by xdlead** [comment]
Some of our clients are currently using these two systems and we need to meet their requirement

**Comment by vadimgrn** [comment]
Windows 10 x64 Version 1809, OS build 17763) and later are supported. There is no way to support Win7.
