### ISSUE TITLE
[question] is visual studio 2022 supported?

### ISSUE THREAD

**Issue by realivanjx** [vadimgrn/usbip-win2#8]
im wondering if visual studio 2022 with the preview sdk and wdk are supported. or do i need to use visual studio 2019? thanks.

**Comment by vadimgrn** [comment]
I'm waiting for release of WDK for VS-2022. I don't want to install preview versions of SDK/WDK.

**Comment by vadimgrn** [comment]
VS2022 can be used to build "develop" branch.

**Comment by docterling** [comment]
1、
windows 10 professional 2004(for this wsk version,I reinstall my windows to this version)
Microsoft Visual Studio Enterprise 2022 (64 bit) - Current - version 17.2.2
sdk version 10.0.22621.0
wdk version 10.0.22621.0
2、
Install driver/usbip_test.pfx (password: usbip)
"Trusted Root Certification Authority" in "Local Computer" (not current user) and
"Trusted Publishers" in "Local Computer" (not current user)
Set certificate driver signing for usbip_vhci project
bcdedit.exe /set TESTSIGNING ON and reboot
3、
in cmd with administrator priviledge
devcon.exe install usbip_root.inf USBIPWIN\root
after that in device manager,it looks like somethings wrong
![image](https://user-images.githubusercontent.com/13477941/171086038-7e5706c4-0e5f-48db-b1bb-d549e7fab6d7.png)

and the property details:
Windows cannot load the device driver for this hardware. The driver may be damaged or missing. (Code 39)
{driver input point not found}
%hs device driver cannot find the input point %hs in the driver %hs.
any suggestions?
and the previous develop version(not wsk) ok for me

**Comment by docterling** [comment]
yes,I also try that to
![image](https://user-images.githubusercontent.com/13477941/171308017-0176f048-7f72-4fec-9615-29506ca77896.png)
but the problem the same

**Comment by docterling** [comment]
I set this,and it works now!
![image](https://user-images.githubusercontent.com/13477941/171548654-2b2066b6-6d39-4242-ad7e-d98c1bb77202.png)

**Comment by vadimgrn** [comment]
Thank you, I was going to revise these settings of the project.

**Comment by docterling** [comment]
1.this one is when I change the sound volume over the task bar
[BSOD1.log](https://github.com/vadimgrn/usbip-win2/files/8822133/BSOD1.log)
2.this one is do attach-detach-attach,and do the log cmds
[BSOD2.log](https://github.com/vadimgrn/usbip-win2/files/8822150/BSOD2.log)

**Comment by vadimgrn** [comment]
I've fixed several bugs that cause BSOD. I'm testing vhci driver using Driver Verifier and there are no issues so far. Could you please try your devices with new build?

**Comment by docterling** [comment]
1. I do attach-change vol-detach，when attach windows will play the new usb device arriving sound,but The voice sounds trembling，and then I change the sound volume through task bar,the ui seem stuck and no sound,after that I do detach
[attach-change vol-detach.txt](https://github.com/vadimgrn/usbip-win2/files/8866613/attach-change.vol-detach.txt)
2. in 1 after detach I've found the server was crashed and I restart it,and I do attach and change sound volume again,it BSOD
[BSOD3.txt](https://github.com/vadimgrn/usbip-win2/files/8866638/BSOD3.txt)
3. just do attach-detach-attach
[BSOD4-attach-detach-attach.txt](https://github.com/vadimgrn/usbip-win2/files/8866650/BSOD4-attach-detach-attach.txt)

**Comment by vadimgrn** [comment]
Please, make logs exactly as described in "Obtaining USB/IP logs on Windows". Your logs are hard to understand due to another formatting.

**Comment by vadimgrn** [comment]
BSOD4-attach-detach-attach.txt caused by NT_ASSERT, I've commented it.
BSOD3.txt is very similar to behavior of the driver before recent fixes, make sure that you are building and testing the latest develop branch.

**Comment by vadimgrn** [comment]
I've fixed bug that I found in BSOD5-change.vol.txt, thank you!
copy_isoc_data:src_offset(0) != src_len(192)

**Comment by docterling** [comment]
I've tried,when attach it will failed on sending and then auto unplug,here is the etl log file
[LogSession_20220610_093143.zip](https://github.com/vadimgrn/usbip-win2/files/8875146/LogSession_20220610_093143.zip)
I am used to using the traceview.exe,You can navigate to the following line
vhci	wsk.events.cpp	634	WskDisconnectEvent	_**06\10\2022-09:34:03:423**_	vpdo 49ccb420, Flags 0x9

**Comment by vadimgrn** [comment]
I can't and won't view binary file.

**Comment by docterling** [comment]
I've just tried again
the strange thing is the device name in device manager,now it's
![image](https://user-images.githubusercontent.com/13477941/173011657-11c88a46-1371-4858-8d16-b5301ab648eb.png)
it used to be "AUCTOPUS I-65"
but the sound is ok now : )

**Comment by vadimgrn** [comment]
Do you notice a difference between this WSK build and old version that uses usbip_xfer.exe ?

**Comment by docterling** [comment]
xfer first connect to server and get the device-configration descriptor and then create vpdo
wsk first create vpdo and then connect
but when plugin xfer is not use the already got descrptor info
after IoInvalidateDeviceRelations the upper driver will URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE
I know the sting "AUCTOPUS I-65" is frome iProduct string in device descriptor,but I don't know the string "USB Audio Device" from where?

**Comment by vadimgrn** [comment]
Fixed
