### ISSUE TITLE
I hope to add support for wider area networks, and I’m really looking forward to it.

### ISSUE THREAD

**Issue by ethan0371** [vadimgrn/usbip-win2#82]

**Comment by vadimgrn** [comment]
I don't get it, what does it mean? You cannot use something else except TCP/IP for usbip protocol.

**Comment by ethan0371** [comment]
I am very happy to read your reply. I want to build a usbip for server turnover, but I have no direction. I wonder if you can tell me which direction I should start with.

**Comment by vadimgrn** [comment]
I'm going to add a server for this project myself, but currently I don't have enough time to work on it.

**Comment by ethan0371** [comment]
I plan to split the connection between the original USBIP and USBIPD, and then interact with the program through a server on both ends of the split
![微信图片_20240824145251](https://github.com/user-attachments/assets/da3af1a7-de74-40be-ba3d-6d139c49e9c4)

**Comment by ethan0371** [comment]
Looking forward to your answer. Do you think this approach is acceptable?

**Comment by vadimgrn** [comment]
I don't understand what you want. Everything will be implemented in the driver.

**Comment by ethan0371** [comment]
Thank you very much for your reply. If you encounter any problems in the future, I hope to communicate with you again.

**Comment by ethan0371** [comment]
Do you have an account on freelancer?
