### ISSUE TITLE
could you compile a arm64 release version package? please

### ISSUE THREAD

**Issue by lxwAsm** [vadimgrn/usbip-win2#84]

**Comment by vadimgrn** [comment]
I can try, but I don't have arm64 system for the testing

**Comment by vadimgrn** [comment]
Try [this](https://drive.google.com/file/d/1k9apsFKaYeWnNMJjnyJd7RQ7i94euO7O/view?usp=sharing), pls

**Comment by vadimgrn** [comment]
What is the point in asking about the arm64 build and then not giving any feedback?

**Comment by lxwAsm** [comment]
thanks,I have build arm64 version in my pc,it works normal

**Comment by lxwAsm** [comment]
Thank you, author, you are very enthusiastic

**Comment by vadimgrn** [comment]
I want you to try my build, please. I'm going to publish it for all if it works.

**Comment by vadimgrn** [comment]
If you turn test signing on, it should work

**Comment by lxwAsm** [comment]
i turned test signing on when testing.now my pc crashes and can't test....

**Comment by vadimgrn** [comment]
You said that you built it and it works, now you are saying the opposite.

**Comment by lxwAsm** [comment]
yes,but i didn't use the installer to install.I builded its drivers and usbip.exe arm version,then i installed them with company certificate by my code that is the same as your installer. it works fine.I guess wheather the certificate Influences it.

**Comment by vadimgrn** [comment]
OK, thank you. Anyway, I don't have ARM64 Windows PC to find out that.
