### ISSUE TITLE
Both ude and wdm  can not work with this device

### ISSUE THREAD

**Issue by hbsgz008** [vadimgrn/usbip-win2#85]
I have a usb composite device , when use ude driver,  it shows that String descriptors are not available. 
![2](https://github.com/user-attachments/assets/65a3f4cb-351c-45c6-aa3b-4bf00d2fe811)

  
and when I use usbip-win2-0.9.3.4 wdm driver,  there is 3 interfaces  can not  install driver,  and when I use  the usb-win wdm driver, all the interface's drivers are  installed, but the winusb WCID is null. 
![1](https://github.com/user-attachments/assets/fd041827-bd99-4cc5-a578-597ced1bbbed)

**Comment by vadimgrn** [comment]
https://github.com/vadimgrn/usbip-win2/tree/master?tab=readme-ov-file#obtaining-usbip-logs-on-windows

**Comment by hbsgz008** [comment]
this is the ude log:
[logude.txt](https://github.com/user-attachments/files/17057601/logude.txt)

**Comment by vadimgrn** [comment]
This is usb full speed device, its endpoint descriptors should be patched, but it does not work. I can do nothing, I don't have the device to try something.

**Comment by hbsgz008** [comment]
I changed to use wdm driver,  there is no the ude's  problem. but it got BSOD after running for a while.  In the dump file the receive:wsk irp numbers is more than  the  send:wsk irp numbers. 
[bsoddump.txt](https://github.com/user-attachments/files/17094637/bsoddump.txt)

**Comment by vadimgrn** [comment]
WDM driver is no longer supported
