### ISSUE TITLE
Cannot attach several PCs to one USB port at the same time

### ISSUE THREAD

**Issue by w2918000** [vadimgrn/usbip-win2#89]
Hello, my goal is to enable multiple PCs to access the encryption lock on a USB port on the server side simultaneously, but the client prompts that it cannot be attached at the same time. In the absence of relevant driver knowledge, I would like to inquire whether it is feasible to add an intermediate layer within the server driver to receive request signals from multiple PCs simultaneously for unified access to the encryption lock? If that's the case, I want to learn about driving knowledge and give it a try

**Comment by vadimgrn** [comment]
Hello, only one client can be attached to a usb device on server. There is no solution for that usage scenario.
