### ISSUE TITLE
All users can see my device

### ISSUE THREAD

**Issue by hbsgz008** [vadimgrn/usbip-win2#92]
Is there any way to only allow designated users to see my device？Alternatively, User 1 can only see Device 1, while User 2 can only see Devices 2 and 3？

**Comment by vadimgrn** [comment]
What do you mean? Any user can attach any remote device from a server. Do you want to restrict a user to attach particular device(s) only?

**Comment by hbsgz008** [comment]
@vadimgrn  yes，like rdp session isolation。

**Comment by vadimgrn** [comment]
Currently, nothing similar has been implemented
